### ISSUE TITLE
Error: Sigmoid: Can't compute the sigmoidFn for non numerical values, Got NaN

### ISSUE THREAD

**Issue by Ahmed-Emad** [CarmenPopoviciu/neural-net#6]
I always get this error when following Readme instructions:
"Error: Sigmoid: Can't compute the sigmoidFn for non numerical values, Got NaN".

```
neuralNet > let myNet = new NeuralNet();
undefined
neuralNet > myNet.initialise({layers: [2,3,3,1]});
undefined
neuralNet > myNet.train([ [[0,0],[0]], [[0,1],[1]]]);
undefined
neuralNet > myNet.predict([[0,1]]);
Error: Sigmoid: Can't compute the sigmoidFn for non numerical values, Got NaN
    at Object.sigmoid [as fn] (/Users/ahmadbarakat/Documents/GitHub/neural-net/utils/sigmoid.js:14:13)
    at Neuron.updateOutput (/Users/ahmadbarakat/Documents/GitHub/neural-net/neuron.js:110:35)
    at /Users/ahmadbarakat/Documents/GitHub/neural-net/neuralNet.js:372:16
    at Array.forEach (native)
    at /Users/ahmadbarakat/Documents/GitHub/neural-net/neuralNet.js:367:22
    at Array.forEach (native)
    at feedforward (/Users/ahmadbarakat/Documents/GitHub/neural-net/neuralNet.js:366:12)
    at NeuralNet.predict (/Users/ahmadbarakat/Documents/GitHub/neural-net/neuralNet.js:210:12)
    at repl:1:7
    at ContextifyScript.Script.runInContext (vm.js:37:29)
```

**Comment by Ahmed-Emad** [comment]
#7 
This PR fixes a typo in the example in readme 😃 
now:
```
neuralNet > let myNet = new NeuralNet();
undefined
neuralNet > myNet.initialise({layers: [2,3,3,1]});
undefined
neuralNet > myNet.train([ [[0,0],[0]], [[0,1],[1]]]);
undefined
neuralNet > myNet.predict([0,1]);
[ 0.9790844236297308 ]
neuralNet >
```
